sudo: required
services:
  - docker

before_install:
  - docker build -t bes1815/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bes1815/react-test npm test

after_success:
  - docker build -t bes1815/multi-client ./client
  - docker build -t bes1815/multi-worker ./worker
  - docker build -t bes1815/multi-server ./server
  - docker build -t bes1815/multi-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push bes1815/multi-client
  - docker push bes1815/multi-nginx
  - docker push bes1815/multi-server
  - docker push bes1815/multi-worker
